import type { TransactionItemBody } from "~/types/transaction";

export const transactionItems: TransactionItemBody[] = [
  {
    asetName: "Tunai",
    category: "Bisnis",
    date: "2026-03-19T08:30:00.000Z",
    nominal: 450000,
    note: "Penjualan beras dan minyak goreng (pagi)",
    type: "income",
    description: "Pemasukan Warung",
    subCategory: "Penjualan",
  },
  {
    asetName: "Bank Mandiri",
    category: "Gaji",
    date: "2026-02-25T00:05:00.000Z",
    nominal: 15000000,
    note: "Gaji Full-stack Developer Maret",
    type: "income",
    description: "Salary",
    subCategory: "Pemasukan Tetap",
  },
  {
    asetName: "E-Wallet (Gopay)",
    category: "Makanan",
    date: "2026-03-19T12:15:00.000Z",
    nominal: 45000,
    note: "Makan siang Nasi Padang via GoFood",
    type: "expense",
    description: "Makan Siang",
    subCategory: "Konsumsi",
  },
  {
    asetName: "Bank BCA",
    category: "Investasi",
    date: "2026-03-10T09:00:00.000Z",
    nominal: 1000000,
    note: "Top up RDPU (Auto-debit)",
    type: "expense",
    description: "Investasi Bibit",
    subCategory: "Tabungan",
  },
  {
    asetName: "Tunai",
    category: "Kebutuhan",
    date: "2026-03-18T19:45:00.000Z",
    nominal: 200000,
    note: "Isi token listrik rumah",
    type: "expense",
    description: "Token Listrik",
    subCategory: "Tagihan",
  },
  {
    asetName: "Bank Mandiri",
    category: "Hiburan",
    date: "2026-03-15T14:00:00.000Z",
    nominal: 186000,
    note: "Langganan Netflix Family Plan",
    type: "expense",
    description: "Streaming Service",
    subCategory: "Subscription",
  },
  {
    asetName: "E-Wallet (OVO)",
    category: "Transportasi",
    date: "2026-03-19T17:30:00.000Z",
    nominal: 35000,
    note: "Isi bensin motor (Pertalite)",
    type: "expense",
    description: "Bensin",
    subCategory: "Kendaraan",
  },
  {
    asetName: "Tunai",
    category: "Bisnis",
    date: "2026-03-17T06:00:00.000Z",
    nominal: 1200000,
    note: "Belanja stok barang dagangan ke pasar",
    type: "expense",
    description: "Kulakan Stok",
    subCategory: "Operasional",
  },
];
